# -*- coding: utf-8 -*-
"""SistemaAssistencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us1qoZgc8-9-t4MELCFRBMDwoI_m6f5J
"""

import pandas as pd
import os
import matplotlib.pyplot as plt

arquivo = 'dados_assistencia.csv'

if os.path.exists(arquivo):
    df = pd.read_csv(arquivo)
    print("Base carregada!")
else:
    df = pd.DataFrame(columns=['Data','Lojista','Aparelho','Defeito','Valor'])
    print("Nova base criada!")

df

def salvar():
    df.to_csv('dados_assistencia.csv', index=False)

def adicionar():
    global df

    data = input("Data: ")
    lojista = input("Lojista: ")
    aparelho = input("Aparelho: ")
    defeito = input("Defeito: ")
    valor = float(input("Valor: "))

    novo = pd.DataFrame([[data, lojista, aparelho, defeito, valor]],
                        columns=df.columns)

    df = pd.concat([df, novo], ignore_index=True)
    salvar()

    print("Registro adicionado!")

def ver_dados():
    print(df)

def faturamento_total():
    print("Total:", df['Valor'].sum())

def por_lojista():
    print(df.groupby('Lojista')['Valor'].sum())

def por_defeito():
    print(df.groupby('Defeito')['Valor'].mean())

def menu():
    while True:
        print("\n--- SISTEMA ASSISTÊNCIA ---")
        print("1 - Adicionar registro")
        print("2 - Ver dados")
        print("3 - Faturamento total")
        print("4 - Faturamento por lojista")
        print("5 - Média por defeito")
        print("6 - Gráfico de barras (lojistas)")
        print("7 - Gráfico de pizza (defeitos)")
        print("0 - Sair")

        opcao = input("Escolha: ")

        if opcao == '1':
            adicionar()
        elif opcao == '2':
            ver_dados()
        elif opcao == '3':
            faturamento_total()
        elif opcao == '4':
            por_lojista()
        elif opcao == '5':
            por_defeito()
        elif opcao == '6':
            grafico_barras()
        elif opcao == '7':
            grafico_pizza()
        elif opcao == '0':
            print("Saindo...")
            break
        else:
            print("Opção inválida")

def grafico_barras():
    dados = df.groupby('Lojista')['Valor'].sum()

    dados.plot(kind='bar')
    plt.title('Faturamento por Lojista')
    plt.xlabel('Lojistas')
    plt.ylabel('Valor')
    plt.xticks(rotation=45)
    plt.show()

def grafico_pizza():
    dados = df['Defeito'].value_counts()

    dados.plot(kind='pie', autopct='%1.1f%%')
    plt.title('Frequência de Defeitos')
    plt.ylabel('')
    plt.show()

menu()